[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ip-logger"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"